# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_app', '0006_auto_20171012_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
